//! One adapter per claim family.
//!
//! Every adapter is the same three lines — deserialize the family's own
//! `ClaimSet`, check it says it is what it was filed as, call the family's
//! own `design_claims` — so they are generated by [`family!`]. The registry
//! deliberately holds no claim logic: the family crate is the single source
//! of truth for what its claims mean, and an adapter that "helped" would be
//! a second answer.
//!
//! CAM is the exception, and only because it has more surface to expose:
//! staleness (`restate`) and the measurement loop (`bind` /
//! `close_over_pins`). Even there the adapter only marshals — the arithmetic
//! is `vcad_kernel_cam::receipt`'s.

/// Generate a family adapter from its crate's `receipt` module.
///
/// Every family's module exposes the same four items — `CLAIM_SCHEMA`,
/// `RECEIPT_DOMAIN`, `ClaimSet`, `design_claims` — which is what makes one
/// registry possible at all.
macro_rules! family {
    (
        $(#[$meta:meta])*
        $feature:literal => $name:ident, $receipt:path, $crate_name:literal, $summary:literal
    ) => {
        #[cfg(feature = $feature)]
        $(#[$meta])*
        pub mod $name {
            use $receipt as family;

            use crate::{ClaimFamily, RegistryError};
            use vcad_receipt::ReceiptClaim;

            /// Deserialize this family's report and translate it.
            fn to_claims(report_json: &str) -> Result<Vec<ReceiptClaim>, RegistryError> {
                let set: family::ClaimSet = serde_json::from_str(report_json)
                    .map_err(|e| RegistryError::bad_report(family::CLAIM_SCHEMA, e))?;
                // A report filed under the wrong family would be translated
                // by the wrong ladder and read as evidence of something
                // nobody checked. Refuse it.
                if set.schema != family::CLAIM_SCHEMA {
                    return Err(RegistryError::SchemaMismatch {
                        schema: family::CLAIM_SCHEMA.to_string(),
                        found: set.schema.clone(),
                    });
                }
                Ok(family::design_claims(&set))
            }

            /// This family's registry entry.
            pub fn family() -> ClaimFamily {
                ClaimFamily {
                    schema: family::CLAIM_SCHEMA,
                    domain: family::RECEIPT_DOMAIN,
                    crate_name: $crate_name,
                    summary: $summary,
                    native_only: false,
                    to_claims,
                    restate: None,
                    bind: None,
                }
            }
        }
    };
}

family!(
    "tolerance" => tolerance, vcad_kernel_tolerance::receipt, "vcad-kernel-tolerance",
    "dimensional stackups: worst-case / RSS / Monte-Carlo closure against a requirement"
);
family!(
    "thermal" => thermal, vcad_kernel_thermal::receipt, "vcad-kernel-thermal",
    "conduction: peak temperature, rise above ambient, thermal resistance"
);
family!(
    "em" => em, vcad_kernel_em::receipt, "vcad-kernel-em",
    "magneto/electrostatics: inductance, force, field, cross-route residual"
);
family!(
    "photonics" => photonics, vcad_kernel_photonics::receipt, "vcad-kernel-photonics",
    "2D FDTD: transmission, insertion loss, crosstalk for a fab-ready layout"
);
family!(
    "antenna" => antenna, vcad_kernel_antenna::receipt, "vcad-kernel-antenna",
    "thin-wire MoM: input impedance, S11, gain, thin-wire validity gates"
);
family!(
    "neutronics" => neutronics, vcad_kernel_neutronics::receipt, "vcad-kernel-neutronics",
    "shielding: transmitted flux and H*(10) dose behind a stack"
);
family!(
    "acoustics" => acoustics, vcad_kernel_acoustics::receipt, "vcad-kernel-acoustics",
    "air-side Helmholtz: port tuning, mode frequencies, radiated pressure"
);
family!(
    "particle" => particle, vcad_kernel_particle::receipt, "vcad-kernel-particle",
    "charged-particle optics: interception, transparency, D-D rate, Q"
);
family!(
    "fea" => fea, vcad_kernel_fea::receipt, "vcad-kernel-fea",
    "linear-elastic FEA: peak stress, displacement, safety factor, convergence"
);
family!(
    "flow" => flow, vcad_kernel_flow::receipt, "vcad-kernel-flow",
    "lattice-Boltzmann: pressure drop, flow rate, mass audit, heat pickup"
);
family!(
    "optics" => optics, vcad_kernel_optics::receipt, "vcad-kernel-optics",
    "ray optics: spot size, wavefront error, throughput"
);
family!(
    "orbit" => orbit, vcad_kernel_orbit::receipt, "vcad-kernel-orbit",
    "orbital mechanics: delta-v, period, station-keeping budget"
);
family!(
    "spice" => spice, vcad_ecad_sim::circuit::receipt, "vcad-ecad-sim",
    "circuit simulation: node voltages, currents, timing against a spec"
);

#[cfg(feature = "cam")]
pub mod cam;
