//! Excellon drill file writer.
//!
//! Generates an Excellon NC drill file (`.drl`) from PCB data. Holes are
//! collected from through-hole pads (THT/NPTH) and vias, grouped by drill
//! diameter, and assigned sequential tool numbers.

use std::collections::BTreeMap;
use std::io::Write;

use vcad_ir::ecad::*;

/// Errors that can occur during Excellon generation.
#[derive(Debug, thiserror::Error)]
pub enum ExcellonError {
    /// An I/O error occurred while writing.
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// The PCB contains no drill holes.
    #[error("no drill holes found in PCB")]
    NoDrills,
}

/// A single drill hit (hole location).
#[derive(Debug, Clone)]
struct DrillHit {
    x: f64,
    y: f64,
}

/// Collect all drill holes from the PCB grouped by diameter.
///
/// Returns a `BTreeMap` so tools are ordered by ascending diameter. The key is
/// the diameter in mm rounded to 4 decimal places (encoded as an integer in
/// units of 0.0001 mm for exact comparison).
fn collect_holes(pcb: &Pcb) -> BTreeMap<i64, Vec<DrillHit>> {
    let mut holes: BTreeMap<i64, Vec<DrillHit>> = BTreeMap::new();

    // Holes from footprint pads.
    for fp in &pcb.footprints {
        let cos_r = fp.rotation.to_radians().cos();
        let sin_r = fp.rotation.to_radians().sin();

        for pad in &fp.pads {
            if let Some(ref drill) = pad.drill {
                let lx = pad.position.x * cos_r - pad.position.y * sin_r;
                let ly = pad.position.x * sin_r + pad.position.y * cos_r;
                let x = fp.position.x + lx;
                let y = fp.position.y + ly;
                let key = (drill.diameter * 10_000.0).round() as i64;
                holes.entry(key).or_default().push(DrillHit { x, y });
            }
        }
    }

    // Holes from vias.
    for via in &pcb.vias {
        let key = (via.drill * 10_000.0).round() as i64;
        holes.entry(key).or_default().push(DrillHit {
            x: via.position.x,
            y: via.position.y,
        });
    }

    holes
}

/// Generate Excellon drill file content.
///
/// Writes the complete Excellon file (header with tool definitions, drill hit
/// coordinates, and footer) to `writer`. Coordinates are in metric (mm) with
/// 4 decimal places.
pub fn write_excellon<W: Write>(writer: &mut W, pcb: &Pcb) -> Result<(), ExcellonError> {
    let holes = collect_holes(pcb);

    // Header.
    writeln!(writer, "M48")?;
    writeln!(writer, ";Generated by vcad-ecad-export")?;
    writeln!(writer, ";FORMAT={{-:-/ absolute / metric / decimal}}")?;
    writeln!(writer, "FMAT,2")?;
    writeln!(writer, "METRIC,TZ")?;

    // Tool definitions.
    let tools: Vec<(u32, f64, &Vec<DrillHit>)> = holes
        .iter()
        .enumerate()
        .map(|(i, (key, hits))| {
            let tool_num = (i + 1) as u32;
            let diameter = *key as f64 / 10_000.0;
            (tool_num, diameter, hits)
        })
        .collect();

    for &(tool_num, diameter, _) in &tools {
        writeln!(writer, "T{tool_num:02}C{diameter:.4}")?;
    }

    writeln!(writer, "%")?;

    // Drill body.
    writeln!(writer, "G90")?;
    writeln!(writer, "G05")?;

    for &(tool_num, _, hits) in &tools {
        writeln!(writer, "T{tool_num:02}")?;
        for hit in hits {
            writeln!(writer, "X{:.4}Y{:.4}", hit.x, hit.y)?;
        }
    }

    // Footer.
    writeln!(writer, "T0")?;
    writeln!(writer, "M30")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vcad_ir::Vec2;

    fn test_pcb() -> Pcb {
        Pcb {
            outline: BoardOutline {
                vertices: vec![
                    Vec2::new(0.0, 0.0),
                    Vec2::new(50.0, 0.0),
                    Vec2::new(50.0, 40.0),
                    Vec2::new(0.0, 40.0),
                ],
                cutouts: vec![],
                thickness: 1.6,
            },
            stackup: LayerStackup {
                layers: vec![StackupLayer {
                    layer: PcbLayer::FCu,
                    copper_thickness: Some(0.035),
                    dielectric_thickness: None,
                    dielectric_er: None,
                    material: None,
                }],
            },
            nets: vec![Net {
                id: "1".into(),
                name: "VCC".into(),
            }],
            rules: DesignRules {
                default_rules: NetClassRules {
                    name: "Default".into(),
                    trace_width: 0.25,
                    clearance: 0.2,
                    via_diameter: 0.8,
                    via_drill: 0.4,
                    diff_pair_gap: None,
                    diff_pair_width: None,
                },
                class_rules: vec![],
                net_class_assignments: Default::default(),
                edge_clearance: 0.5,
                hole_to_hole: 0.5,
                min_annular_ring: 0.15,
                min_drill: 0.2,
            },
            footprints: vec![Footprint {
                reference: "J1".into(),
                value: "Conn_01x03".into(),
                footprint_name: "Connector:PinHeader_1x03_P2.54mm".into(),
                position: Vec2::new(10.0, 20.0),
                rotation: 0.0,
                front: true,
                pads: vec![
                    Pad {
                        number: "1".into(),
                        pad_type: PadType::THT,
                        shape: PadShape::Circle { diameter: 1.7 },
                        position: Vec2::new(0.0, 0.0),
                        rotation: 0.0,
                        drill: Some(DrillSpec {
                            diameter: 1.0,
                            oval: false,
                            oval_height: None,
                        }),
                        net: Some("1".into()),
                        layers: vec![PcbLayer::FCu, PcbLayer::BCu],
                    },
                    Pad {
                        number: "2".into(),
                        pad_type: PadType::THT,
                        shape: PadShape::Circle { diameter: 1.7 },
                        position: Vec2::new(2.54, 0.0),
                        rotation: 0.0,
                        drill: Some(DrillSpec {
                            diameter: 1.0,
                            oval: false,
                            oval_height: None,
                        }),
                        net: None,
                        layers: vec![PcbLayer::FCu, PcbLayer::BCu],
                    },
                    Pad {
                        number: "3".into(),
                        pad_type: PadType::THT,
                        shape: PadShape::Circle { diameter: 1.7 },
                        position: Vec2::new(5.08, 0.0),
                        rotation: 0.0,
                        drill: Some(DrillSpec {
                            diameter: 1.0,
                            oval: false,
                            oval_height: None,
                        }),
                        net: None,
                        layers: vec![PcbLayer::FCu, PcbLayer::BCu],
                    },
                ],
                graphics: vec![],
                model_3d: None,
                properties: Default::default(),
            }],
            traces: vec![],
            trace_arcs: vec![],
            vias: vec![Via {
                position: Vec2::new(30.0, 20.0),
                diameter: 0.8,
                drill: 0.3,
                start_layer: PcbLayer::FCu,
                end_layer: PcbLayer::BCu,
                net: "1".into(),
                source: None,
            }],
            zones: vec![],
            keepouts: vec![],
            net_ties: vec![],
        }
    }

    #[test]
    fn excellon_header() {
        let pcb = test_pcb();
        let mut buf = Vec::new();
        write_excellon(&mut buf, &pcb).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.starts_with("M48\n"), "missing M48 header");
        assert!(output.contains("METRIC"), "missing METRIC declaration");
    }

    #[test]
    fn excellon_tool_definitions() {
        let pcb = test_pcb();
        let mut buf = Vec::new();
        write_excellon(&mut buf, &pcb).unwrap();
        let output = String::from_utf8(buf).unwrap();

        // Two tool sizes: 0.3 mm (via) and 1.0 mm (THT pads).
        assert!(output.contains("T01C0.3000"), "missing 0.3mm tool");
        assert!(output.contains("T02C1.0000"), "missing 1.0mm tool");
    }

    #[test]
    fn excellon_coordinates() {
        let pcb = test_pcb();
        let mut buf = Vec::new();
        write_excellon(&mut buf, &pcb).unwrap();
        let output = String::from_utf8(buf).unwrap();

        // Via at (30, 20).
        assert!(
            output.contains("X30.0000Y20.0000"),
            "missing via coordinate"
        );
        // First THT pad at (10, 20).
        assert!(
            output.contains("X10.0000Y20.0000"),
            "missing pad 1 coordinate"
        );
    }

    #[test]
    fn excellon_footer() {
        let pcb = test_pcb();
        let mut buf = Vec::new();
        write_excellon(&mut buf, &pcb).unwrap();
        let output = String::from_utf8(buf).unwrap();

        assert!(output.contains("T0\n"), "missing T0 (tool deselect)");
        assert!(output.contains("M30\n"), "missing M30 end command");
    }

    #[test]
    fn excellon_groups_holes_by_diameter() {
        let pcb = test_pcb();
        let holes = collect_holes(&pcb);

        // Two distinct diameters: 0.3 mm (via) and 1.0 mm (THT).
        assert_eq!(holes.len(), 2);

        let key_03 = (0.3_f64 * 10_000.0).round() as i64;
        let key_10 = (1.0_f64 * 10_000.0).round() as i64;

        assert_eq!(holes[&key_03].len(), 1, "expected 1 via hole");
        assert_eq!(holes[&key_10].len(), 3, "expected 3 THT pad holes");
    }
}
