/**
 * Auto-generated by wasmosis
 * Do not edit manually
 */

import { createRegistry, defineModule } from 'wasmosis';

export const core = defineModule({
  name: 'core',
  loader: () => fetch('./core.wasm').then(r => r.arrayBuffer()),
  
  
});

export const sweep = defineModule({
  name: 'sweep',
  loader: () => fetch('./sweep.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const gpu = defineModule({
  name: 'gpu',
  loader: () => fetch('./gpu.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const advanced = defineModule({
  name: 'advanced',
  loader: () => fetch('./advanced.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const ml = defineModule({
  name: 'ml',
  loader: () => fetch('./ml.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const patterns = defineModule({
  name: 'patterns',
  loader: () => fetch('./patterns.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const drafting = defineModule({
  name: 'drafting',
  loader: () => fetch('./drafting.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const step = defineModule({
  name: 'step',
  loader: () => fetch('./step.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const physics = defineModule({
  name: 'physics',
  loader: () => fetch('./physics.wasm').then(r => r.arrayBuffer()),
  depends: ['core'],
  
});

export const registry = createRegistry({ core, sweep, gpu, advanced, ml, patterns, drafting, step, physics });

export { core };
export { sweep };
export { gpu };
export { advanced };
export { ml };
export { patterns };
export { drafting };
export { step };
export { physics };
