//! Structure import/export.
//!
//! Ships an XYZ reader/writer (including the `Lattice="..."` extended-XYZ
//! convention for periodic cells) and covalent-radius bond perception. PDB and
//! CIF readers follow the same shape; XYZ is the reference implementation.

use crate::element;
use crate::vec3;
use vcad_ir::molecule::{Bond, Cell, MoleculeSystem, Species};

/// Errors from parsing structure files.
#[derive(Debug, thiserror::Error)]
pub enum IoError {
    /// The file was empty or truncated.
    #[error("unexpected end of input at line {0}")]
    UnexpectedEof(usize),
    /// A line could not be parsed.
    #[error("parse error at line {line}: {msg}")]
    Parse {
        /// 1-based line number.
        line: usize,
        /// Description.
        msg: String,
    },
}

/// Parse an XYZ (or extended-XYZ) string into a [`MoleculeSystem`].
///
/// Standard layout: first line atom count, second line a free-form comment
/// (scanned for `Lattice="ax ay az bx by bz cx cy cz"`), then one
/// `symbol x y z` line per atom. Bonds are perceived from covalent radii.
pub fn parse_xyz(text: &str) -> Result<MoleculeSystem, IoError> {
    let mut lines = text.lines().enumerate();
    let (_, count_line) = lines.next().ok_or(IoError::UnexpectedEof(1))?;
    let count: usize = count_line.trim().parse().map_err(|_| IoError::Parse {
        line: 1,
        msg: format!("expected atom count, got {count_line:?}"),
    })?;
    let (comment_no, comment) = lines.next().ok_or(IoError::UnexpectedEof(2))?;
    let cell = parse_lattice(comment).map_err(|msg| IoError::Parse {
        line: comment_no + 1,
        msg,
    })?;

    let mut species: Vec<Species> = Vec::new();
    let mut species_idx: Vec<u32> = Vec::with_capacity(count);
    let mut positions: Vec<[f64; 3]> = Vec::with_capacity(count);

    for _ in 0..count {
        let (line_no, line) = lines.next().ok_or(IoError::UnexpectedEof(count + 2))?;
        let mut it = line.split_whitespace();
        let sym = it.next().ok_or_else(|| IoError::Parse {
            line: line_no + 1,
            msg: "missing element symbol".into(),
        })?;
        let coords: Vec<f64> = it
            .take(3)
            .map(|t| t.parse::<f64>())
            .collect::<Result<_, _>>()
            .map_err(|_| IoError::Parse {
                line: line_no + 1,
                msg: format!("bad coordinate in {line:?}"),
            })?;
        if coords.len() < 3 {
            return Err(IoError::Parse {
                line: line_no + 1,
                msg: format!("expected 3 coordinates in {line:?}"),
            });
        }
        let elem = element::normalize_symbol(sym);
        let data = element::lookup(&elem);
        let idx = species
            .iter()
            .position(|s| s.element == elem)
            .unwrap_or_else(|| {
                species.push(Species {
                    element: elem.clone(),
                    atomic_number: data.number,
                    mass: data.mass,
                    charge: 0.0,
                    label: None,
                    radius: None,
                    color: None,
                });
                species.len() - 1
            });
        species_idx.push(idx as u32);
        positions.push([coords[0], coords[1], coords[2]]);
    }

    let mut mol = MoleculeSystem {
        species,
        positions,
        species_idx,
        velocities: Vec::new(),
        bonds: Vec::new(),
        cell,
        name: None,
    };
    mol.bonds = perceive_bonds(&mol, 1.2);
    Ok(mol)
}

fn parse_lattice(comment: &str) -> Result<Option<Cell>, String> {
    let Some(start) = comment.find("Lattice=\"") else {
        return Ok(None);
    };
    let rest = &comment[start + "Lattice=\"".len()..];
    let end = rest.find('"').ok_or("unterminated Lattice=\"...\"")?;
    let nums: Vec<f64> = rest[..end]
        .split_whitespace()
        .map(|t| t.parse::<f64>())
        .collect::<Result<_, _>>()
        .map_err(|_| "non-numeric value in Lattice".to_string())?;
    if nums.len() != 9 {
        return Err(format!("Lattice needs 9 numbers, got {}", nums.len()));
    }
    Ok(Some(Cell {
        a: [nums[0], nums[1], nums[2]],
        b: [nums[3], nums[4], nums[5]],
        c: [nums[6], nums[7], nums[8]],
        periodic: [true, true, true],
    }))
}

/// Serialize a [`MoleculeSystem`] to XYZ text (extended-XYZ when a cell exists).
pub fn write_xyz(mol: &MoleculeSystem) -> String {
    let mut out = String::new();
    out.push_str(&format!("{}\n", mol.len()));
    if let Some(c) = &mol.cell {
        out.push_str(&format!(
            "Lattice=\"{} {} {} {} {} {} {} {} {}\"\n",
            c.a[0], c.a[1], c.a[2], c.b[0], c.b[1], c.b[2], c.c[0], c.c[1], c.c[2]
        ));
    } else {
        out.push_str(mol.name.as_deref().unwrap_or("generated by vcad"));
        out.push('\n');
    }
    for i in 0..mol.len() {
        let p = mol.positions[i];
        out.push_str(&format!(
            "{} {:.6} {:.6} {:.6}\n",
            mol.element_of(i),
            p[0],
            p[1],
            p[2]
        ));
    }
    out
}

/// Perceive bonds from covalent radii: atoms `i,j` are bonded when their
/// separation is below `(rcov_i + rcov_j) * tolerance`. O(N²) — adequate for
/// small/medium structures; large systems should use a cell list.
pub fn perceive_bonds(mol: &MoleculeSystem, tolerance: f64) -> Vec<Bond> {
    let n = mol.len();
    let radii: Vec<f64> = (0..n)
        .map(|i| element::lookup(mol.element_of(i)).covalent_radius)
        .collect();
    let mut bonds = Vec::new();
    for i in 0..n {
        for j in (i + 1)..n {
            let cutoff = (radii[i] + radii[j]) * tolerance;
            let d = vec3::sub(mol.positions[i], mol.positions[j]);
            // Skip zero-distance duplicates.
            let r2 = vec3::norm2(d);
            if r2 > 0.16 && r2 < cutoff * cutoff {
                bonds.push(Bond {
                    a: i as u32,
                    b: j as u32,
                    order: 1.0,
                });
            }
        }
    }
    bonds
}
