//! Intermediate representation for the vcad CAD ecosystem.
//!
//! This crate defines the DAG-based IR that represents parametric CAD models.
//! It is shared between the Rust and TypeScript sides of the vcad ecosystem.
//!
//! The IR is purely declarative — no mesh data, just a graph of operations.
//! Evaluation (meshing) is handled separately by the engine.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub mod ecad;
pub mod file_io;
pub mod to_loon;
pub mod vcode;

pub use vcad_tool_derive::ToolSchema;

/// A tool schema entry generated by the ToolSchema derive macro.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolSchemaEntry {
    /// Variant name in snake_case (e.g. "cube", "extrude").
    pub name: String,
    /// Description from doc comments.
    pub description: String,
    /// Category (e.g. "primitive", "sketch_op", "modifier").
    pub category: String,
    /// Optional AI hint for the system prompt.
    pub ai_hint: Option<String>,
    /// JSON Schema for the variant's fields.
    pub input_schema: serde_json::Value,
}

// ============================================================================
// Assembly types (for kinematics)
// ============================================================================

/// 3D transform (translation, rotation in degrees, scale).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Transform3D {
    /// Translation offset.
    pub translation: Vec3,
    /// Rotation angles in degrees (Euler XYZ).
    pub rotation: Vec3,
    /// Scale factors per axis.
    pub scale: Vec3,
}

impl Default for Transform3D {
    fn default() -> Self {
        Self {
            translation: Vec3::new(0.0, 0.0, 0.0),
            rotation: Vec3::new(0.0, 0.0, 0.0),
            scale: Vec3::new(1.0, 1.0, 1.0),
        }
    }
}

impl Transform3D {
    /// Create an identity transform (no translation, rotation, or scaling).
    pub fn identity() -> Self {
        Self::default()
    }
}

/// Joint limits as `[min, max]` tuple for constrained joints.
pub type JointLimits = (f64, f64);

/// Joint kind variants for assembly joints.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum JointKind {
    /// Fixed joint — no degrees of freedom.
    Fixed,
    /// Revolute joint — rotation around an axis.
    Revolute {
        /// Rotation axis.
        axis: Vec3,
        /// Optional angle limits in degrees.
        #[serde(skip_serializing_if = "Option::is_none")]
        limits: Option<JointLimits>,
    },
    /// Slider joint — translation along an axis.
    Slider {
        /// Translation axis.
        axis: Vec3,
        /// Optional position limits in mm.
        #[serde(skip_serializing_if = "Option::is_none")]
        limits: Option<JointLimits>,
    },
    /// Cylindrical joint — rotation and translation along an axis.
    Cylindrical {
        /// Axis of rotation/translation.
        axis: Vec3,
    },
    /// Ball joint — rotation around all axes.
    Ball,
}

/// A joint connecting two instances in an assembly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Joint {
    /// Unique identifier.
    pub id: String,
    /// Optional human-readable name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Parent instance ID (null for world-grounded joints).
    #[serde(rename = "parentInstanceId")]
    pub parent_instance_id: Option<String>,
    /// Child instance ID.
    #[serde(rename = "childInstanceId")]
    pub child_instance_id: String,
    /// Anchor point on parent (or world origin if parent is null).
    #[serde(rename = "parentAnchor")]
    pub parent_anchor: Vec3,
    /// Anchor point on child.
    #[serde(rename = "childAnchor")]
    pub child_anchor: Vec3,
    /// Joint type and parameters.
    pub kind: JointKind,
    /// Current joint state (angle in degrees or position in mm).
    pub state: f64,
}

/// An instance of a part definition in an assembly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Instance {
    /// Unique identifier.
    pub id: String,
    /// Reference to the part definition.
    #[serde(rename = "partDefId")]
    pub part_def_id: String,
    /// Optional human-readable name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional transform override.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform: Option<Transform3D>,
    /// Optional material override.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub material: Option<String>,
}

/// Alias for [`Instance`] (used in some components).
pub type PartInstance = Instance;

/// A reusable part definition in an assembly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PartDef {
    /// Unique identifier.
    pub id: String,
    /// Optional human-readable name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Root node of the geometry DAG.
    pub root: NodeId,
    /// Default material key.
    #[serde(rename = "defaultMaterial", skip_serializing_if = "Option::is_none")]
    pub default_material: Option<String>,
}

// ============================================================================
// Core IR types
// ============================================================================

/// Unique identifier for a node in the IR graph.
pub type NodeId = u64;

/// 2D vector with f64 components (for sketch coordinates).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Vec2 {
    /// X component.
    pub x: f64,
    /// Y component.
    pub y: f64,
}

impl Vec2 {
    /// Create a new Vec2.
    pub fn new(x: f64, y: f64) -> Self {
        Self { x, y }
    }

    /// Euclidean length.
    pub fn length(self) -> f64 {
        (self.x * self.x + self.y * self.y).sqrt()
    }

    /// Unit vector (returns zero if degenerate).
    pub fn normalize(self) -> Vec2 {
        let len = self.length();
        if len < f64::EPSILON {
            Vec2::new(0.0, 0.0)
        } else {
            Vec2::new(self.x / len, self.y / len)
        }
    }

    /// Dot product.
    pub fn dot(self, other: Vec2) -> f64 {
        self.x * other.x + self.y * other.y
    }

    /// 90° CCW rotation: `(-y, x)`.
    pub fn perp(self) -> Vec2 {
        Vec2::new(-self.y, self.x)
    }

    /// Scalar multiply.
    pub fn scale(self, s: f64) -> Vec2 {
        Vec2::new(self.x * s, self.y * s)
    }
}

impl std::ops::Add for Vec2 {
    type Output = Vec2;
    fn add(self, rhs: Vec2) -> Vec2 {
        Vec2::new(self.x + rhs.x, self.y + rhs.y)
    }
}

impl std::ops::Sub for Vec2 {
    type Output = Vec2;
    fn sub(self, rhs: Vec2) -> Vec2 {
        Vec2::new(self.x - rhs.x, self.y - rhs.y)
    }
}

impl std::ops::Mul<f64> for Vec2 {
    type Output = Vec2;
    fn mul(self, rhs: f64) -> Vec2 {
        Vec2::new(self.x * rhs, self.y * rhs)
    }
}

impl std::ops::Neg for Vec2 {
    type Output = Vec2;
    fn neg(self) -> Vec2 {
        Vec2::new(-self.x, -self.y)
    }
}

/// 3D vector with f64 components (conventionally millimeters).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Vec3 {
    /// X component.
    pub x: f64,
    /// Y component.
    pub y: f64,
    /// Z component.
    pub z: f64,
}

impl Vec3 {
    /// Create a new Vec3.
    pub fn new(x: f64, y: f64, z: f64) -> Self {
        Self { x, y, z }
    }
}

/// Text alignment options for 2D text geometry.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum TextAlignment {
    /// Align text to the left (default).
    #[default]
    Left,
    /// Align text to the center.
    Center,
    /// Align text to the right.
    Right,
}

/// A segment of a 2D sketch profile.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SketchSegment2D {
    /// A line segment from start to end.
    Line {
        /// Start point in 2D sketch coordinates.
        start: Vec2,
        /// End point in 2D sketch coordinates.
        end: Vec2,
    },
    /// A circular arc from start to end around a center.
    Arc {
        /// Start point in 2D sketch coordinates.
        start: Vec2,
        /// End point in 2D sketch coordinates.
        end: Vec2,
        /// Center of the arc in 2D sketch coordinates.
        center: Vec2,
        /// If true, arc goes counter-clockwise from start to end.
        ccw: bool,
    },
}

/// A straight line path from start to end.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PathCurve {
    /// A straight line from start to end.
    Line {
        /// Start point.
        start: Vec3,
        /// End point.
        end: Vec3,
    },
    /// A helical path.
    Helix {
        /// Helix radius.
        radius: f64,
        /// Pitch (height per turn).
        pitch: f64,
        /// Total height.
        height: f64,
        /// Number of turns.
        turns: f64,
    },
}

// ============================================================================
// Embroidery types
// ============================================================================

/// A thread color in an embroidery design.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EmbroideryThread {
    /// RGB color.
    pub color: [u8; 3],
    /// Thread name.
    pub name: String,
}

/// Stitch fill strategy.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FillType {
    /// Automatic fill stitch.
    Fill,
    /// Satin stitch.
    Satin,
    /// Running stitch.
    Running,
    /// Manual / pre-digitized stitches.
    Manual,
}

/// Parameters controlling how a stitch group is filled.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct FillParams {
    /// Fill strategy.
    pub fill_type: FillType,
    /// Fill angle in degrees.
    pub angle_deg: f64,
    /// Row spacing in mm.
    pub density_mm: f64,
    /// Whether to add underlay stitches.
    pub underlay: bool,
    /// Maximum stitch length in mm.
    pub max_stitch_length_mm: f64,
}

/// A group of stitches sharing a thread color.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IrStitchGroup {
    /// Index into the design's thread palette.
    pub thread_index: usize,
    /// Stitch positions as flat `[x, y]` pairs in mm.
    pub stitches: Vec<[f64; 2]>,
    /// Optional fill parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fill_params: Option<FillParams>,
}

/// An embroidery design for the IR.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EmbroideryDesign {
    /// Thread palette.
    pub threads: Vec<EmbroideryThread>,
    /// Stitch groups.
    pub stitch_groups: Vec<IrStitchGroup>,
    /// Hoop width in mm.
    pub hoop_width: f64,
    /// Hoop height in mm.
    pub hoop_height: f64,
}

/// CSG operation — the core building block of the IR DAG.
///
/// Each variant is either a leaf primitive or a combining/transform operation
/// that references child nodes by [`NodeId`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToolSchema)]
#[serde(tag = "type")]
#[tool(category = "modeling")]
pub enum CsgOp {
    #[tool(
        category = "primitive",
        ai_hint = "Use for rectangular/box shapes. Size is width(x), depth(y), height(z)."
    )]
    /// Axis-aligned box centered at origin.
    Cube {
        /// Size along each axis.
        size: Vec3,
    },
    #[tool(
        category = "primitive",
        ai_hint = "Axis along Z. Use for round shapes, pins, holes."
    )]
    /// Cylinder along the Z axis, centered at origin.
    Cylinder {
        /// Radius of the cylinder.
        radius: f64,
        /// Height of the cylinder.
        height: f64,
        /// Number of circular segments (0 = auto).
        segments: u32,
    },
    #[tool(category = "primitive")]
    /// Sphere centered at origin.
    Sphere {
        /// Radius of the sphere.
        radius: f64,
        /// Number of circular segments (0 = auto).
        segments: u32,
    },
    #[tool(category = "primitive")]
    /// Cone along the Z axis, centered at origin.
    Cone {
        /// Bottom radius.
        radius_bottom: f64,
        /// Top radius (0 for a point).
        radius_top: f64,
        /// Height of the cone.
        height: f64,
        /// Number of circular segments (0 = auto).
        segments: u32,
    },
    #[tool(hidden)]
    /// Empty geometry (identity for union).
    Empty,
    #[tool(category = "boolean")]
    /// Boolean union of two geometries.
    Union {
        /// Left operand.
        left: NodeId,
        /// Right operand.
        right: NodeId,
    },
    #[tool(category = "boolean")]
    /// Boolean difference (left minus right).
    Difference {
        /// Left operand (base).
        left: NodeId,
        /// Right operand (subtracted).
        right: NodeId,
    },
    #[tool(category = "boolean")]
    /// Boolean intersection of two geometries.
    Intersection {
        /// Left operand.
        left: NodeId,
        /// Right operand.
        right: NodeId,
    },
    #[tool(category = "transform")]
    /// Translation by an offset vector.
    Translate {
        /// Child node to translate.
        child: NodeId,
        /// Translation offset.
        offset: Vec3,
    },
    #[tool(category = "transform")]
    /// Rotation by Euler angles in degrees (applied as X, then Y, then Z).
    Rotate {
        /// Child node to rotate.
        child: NodeId,
        /// Rotation angles in degrees.
        angles: Vec3,
    },
    #[tool(category = "transform")]
    /// Non-uniform scale.
    Scale {
        /// Child node to scale.
        child: NodeId,
        /// Scale factors per axis.
        factor: Vec3,
    },
    #[tool(
        category = "sketch_op",
        ai_hint = "Defines a closed 2D profile. Segments are Line{start,end} or Arc{start,end,center,ccw}. Usually used inline with extrude/revolve — prefer creating extrude directly with inline sketch."
    )]
    /// A 2D sketch profile on a plane.
    ///
    /// The sketch defines a closed profile in a local 2D coordinate system.
    /// Use with [`CsgOp::Extrude`] or [`CsgOp::Revolve`] to create 3D geometry.
    Sketch2D {
        /// Origin point of the sketch plane in 3D.
        origin: Vec3,
        /// Unit vector along the local X axis.
        x_dir: Vec3,
        /// Unit vector along the local Y axis.
        y_dir: Vec3,
        /// The segments forming the closed profile.
        segments: Vec<SketchSegment2D>,
    },
    #[tool(
        category = "sketch_op",
        ai_hint = "PREFERRED for custom shapes. Pass sketch as inline object with origin, x_dir, y_dir, segments. Example: {sketch: {origin:{x:0,y:0,z:0}, x_dir:{x:1,y:0,z:0}, y_dir:{x:0,y:1,z:0}, segments:[{type:'Line',start:{x:0,y:0},end:{x:20,y:0}},{type:'Line',start:{x:20,y:0},end:{x:20,y:15}},{type:'Line',start:{x:20,y:15},end:{x:0,y:15}},{type:'Line',start:{x:0,y:15},end:{x:0,y:0}}]}, direction:{x:0,y:0,z:10}}"
    )]
    /// Extrude a sketch profile along a direction vector.
    Extrude {
        /// The sketch node to extrude.
        sketch: NodeId,
        /// Extrusion direction and distance (length of vector = extrusion depth).
        direction: Vec3,
        /// Optional twist angle in radians (rotation around extrusion axis).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        twist_angle: Option<f64>,
        /// Optional scale factor at end of extrusion (1.0 = no taper).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        scale_end: Option<f64>,
    },
    #[tool(category = "sketch_op")]
    /// Revolve a sketch profile around an axis.
    Revolve {
        /// The sketch node to revolve.
        sketch: NodeId,
        /// A point on the revolution axis.
        axis_origin: Vec3,
        /// Direction of the revolution axis.
        axis_dir: Vec3,
        /// Revolution angle in degrees (360 for full revolution).
        angle_deg: f64,
    },
    #[tool(category = "pattern")]
    /// Linear pattern — repeat geometry along a direction.
    LinearPattern {
        /// Child node to pattern.
        child: NodeId,
        /// Direction vector (will be normalized).
        direction: Vec3,
        /// Number of copies (including original).
        count: u32,
        /// Spacing between copies along direction.
        spacing: f64,
    },
    #[tool(category = "pattern")]
    /// Circular pattern — repeat geometry around an axis.
    CircularPattern {
        /// Child node to pattern.
        child: NodeId,
        /// A point on the rotation axis.
        axis_origin: Vec3,
        /// Direction of the rotation axis.
        axis_dir: Vec3,
        /// Number of copies (including original).
        count: u32,
        /// Total angle span in degrees.
        angle_deg: f64,
    },
    #[tool(
        category = "modifier",
        ai_hint = "Hollow out a solid. Use parent_part_id. Great for enclosures, cups, containers."
    )]
    /// Shell — hollow out a solid by offsetting faces.
    Shell {
        /// Child node to shell.
        child: NodeId,
        /// Wall thickness (inward offset).
        thickness: f64,
    },
    #[tool(
        category = "modifier",
        ai_hint = "Apply after creating geometry. Use parent_part_id to target a part. Typical radius: 1-5mm for small features, 5-20mm for large."
    )]
    /// Fillet — round edges of a solid.
    Fillet {
        /// Child node to fillet.
        child: NodeId,
        /// Fillet radius.
        radius: f64,
    },
    #[tool(
        category = "modifier",
        ai_hint = "Bevel edges. Apply after creating geometry. Use parent_part_id to target a part."
    )]
    /// Chamfer — bevel edges of a solid.
    Chamfer {
        /// Child node to chamfer.
        child: NodeId,
        /// Chamfer distance.
        distance: f64,
    },
    #[tool(category = "sketch_op")]
    /// 2D text that can be extruded into 3D geometry.
    ///
    /// Creates sketch profiles from text glyphs, which can then be
    /// extruded and used in boolean operations for embossing/engraving.
    Text2D {
        /// Origin point of the text plane in 3D.
        origin: Vec3,
        /// X direction of the text plane (text flows along this axis).
        x_dir: Vec3,
        /// Y direction of the text plane (text height along this axis).
        y_dir: Vec3,
        /// The text string to render.
        text: String,
        /// Font name (e.g., "sans-serif", "monospace", or custom registered font).
        font: String,
        /// Text height in mm.
        height: f64,
        /// Letter spacing multiplier (1.0 = normal).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        letter_spacing: Option<f64>,
        /// Line spacing multiplier for multi-line text (1.0 = normal).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        line_spacing: Option<f64>,
        /// Text alignment.
        #[serde(default)]
        alignment: TextAlignment,
    },
    #[tool(category = "sketch_op")]
    /// Sweep a profile along a path curve.
    Sweep {
        /// The sketch node to sweep.
        sketch: NodeId,
        /// The path curve to sweep along.
        path: PathCurve,
        /// Total twist in radians (default 0).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        twist_angle: Option<f64>,
        /// Scale at start (default 1.0).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        scale_start: Option<f64>,
        /// Scale at end (default 1.0).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        scale_end: Option<f64>,
        /// Initial profile rotation around path tangent (radians, default 0).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        orientation: Option<f64>,
        /// Segments along path (0 = auto).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        path_segments: Option<u32>,
        /// Segments per arc in profile (default 8).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        arc_segments: Option<u32>,
    },
    #[tool(category = "sketch_op")]
    /// Loft between multiple profiles.
    Loft {
        /// Array of Sketch2D node references (>= 2).
        sketches: Vec<NodeId>,
        /// Connect last profile to first (creates tube).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        closed: Option<bool>,
    },
    #[tool(hidden)]
    /// Imported pre-tessellated mesh (e.g. from drag-drop STL/GLB).
    ImportedMesh {
        /// Flat array of vertex positions (x, y, z, x, y, z, ...).
        positions: Vec<f64>,
        /// Triangle indices.
        indices: Vec<u32>,
        /// Optional vertex normals (nx, ny, nz, ...).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        normals: Option<Vec<f64>>,
        /// Source filename for display purposes.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        source: Option<String>,
    },
    #[tool(hidden)]
    /// Imported geometry from a STEP file.
    #[serde(rename = "step_import")]
    StepImport {
        /// Path to the STEP file (relative or absolute).
        path: String,
    },
    #[tool(hidden)]
    /// PCB board — evaluates the board's outline + components to 3D geometry.
    /// The `board` field contains the full PCB design data (same ecad::Pcb type).
    PcbBoard { board: Box<crate::ecad::Pcb> },
    #[tool(hidden)]
    /// Embroidery pattern — a 2D stitch design.
    EmbroideryPattern {
        /// The embroidery design data.
        design: Box<EmbroideryDesign>,
    },
}

/// A node in the IR graph.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// Unique identifier.
    pub id: NodeId,
    /// Optional human-readable name.
    pub name: Option<String>,
    /// The operation this node represents.
    pub op: CsgOp,
}

/// PBR material definition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaterialDef {
    /// Material name (e.g. "aluminum", "abs_white").
    pub name: String,
    /// Base color as `[r, g, b]` in 0.0..1.0.
    pub color: [f64; 3],
    /// Metallic factor (0.0 = dielectric, 1.0 = metal).
    pub metallic: f64,
    /// Roughness factor (0.0 = mirror, 1.0 = diffuse).
    pub roughness: f64,
    /// Density in kg/m^3 (for physics simulation).
    pub density: Option<f64>,
    /// Static friction coefficient (for physics simulation).
    pub friction: Option<f64>,
}

/// An entry in the scene — a root node with an assigned material.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SceneEntry {
    /// Root node of this scene part.
    pub root: NodeId,
    /// Material key referencing a [`MaterialDef::name`].
    pub material: String,
    /// If false, the part is hidden from the viewport (default: true).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
}

// ============================================================================
// Scene Settings (lighting, environment, post-processing)
// ============================================================================

/// Available HDR environment presets.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum EnvironmentPreset {
    /// Professional photo studio lighting.
    Studio,
    /// Industrial warehouse with skylights.
    Warehouse,
    /// Modern apartment with natural light.
    Apartment,
    /// Outdoor park environment.
    Park,
    /// Urban city environment.
    City,
    /// Dawn/dusk sky.
    Dawn,
    /// Night environment with artificial lights.
    Night,
    /// Sunset sky.
    Sunset,
    /// Forest environment.
    Forest,
    /// Neutral gray environment for technical views.
    Neutral,
}

/// Environment lighting configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Environment {
    /// Use a preset HDR environment.
    Preset {
        /// The preset to use.
        preset: EnvironmentPreset,
        /// Intensity multiplier (default 1.0).
        #[serde(skip_serializing_if = "Option::is_none")]
        intensity: Option<f64>,
    },
    /// Use a custom HDR environment from URL.
    Custom {
        /// URL to the HDR environment map.
        url: String,
        /// Intensity multiplier (default 1.0).
        #[serde(skip_serializing_if = "Option::is_none")]
        intensity: Option<f64>,
    },
    /// No environment map — uses only direct lights.
    None,
}

/// Type of light source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum LightKind {
    /// Directional light (sun-like, parallel rays).
    Directional {
        /// Direction the light is pointing (normalized).
        direction: Vec3,
    },
    /// Point light (omnidirectional from a point).
    Point {
        /// Position of the light.
        position: Vec3,
        /// Maximum range of the light.
        #[serde(skip_serializing_if = "Option::is_none")]
        distance: Option<f64>,
    },
    /// Spot light (cone of light from a point).
    Spot {
        /// Position of the light.
        position: Vec3,
        /// Direction the spot is pointing.
        direction: Vec3,
        /// Inner cone angle in degrees (full intensity).
        #[serde(skip_serializing_if = "Option::is_none")]
        angle: Option<f64>,
        /// Outer cone angle in degrees (falloff).
        #[serde(skip_serializing_if = "Option::is_none")]
        penumbra: Option<f64>,
    },
    /// Area light (rectangular emitter).
    Area {
        /// Position of the light center.
        position: Vec3,
        /// Direction the light is facing.
        direction: Vec3,
        /// Width of the area light.
        width: f64,
        /// Height of the area light.
        height: f64,
    },
}

/// A light source in the scene.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Light {
    /// Unique identifier for the light.
    pub id: String,
    /// Light type and parameters.
    pub kind: LightKind,
    /// Light color as RGB values (0.0-1.0).
    pub color: [f64; 3],
    /// Light intensity.
    pub intensity: f64,
    /// Whether the light is enabled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Whether this light casts shadows.
    #[serde(rename = "castShadow", skip_serializing_if = "Option::is_none")]
    pub cast_shadow: Option<bool>,
}

/// Background configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Background {
    /// Use the environment map as background.
    Environment,
    /// Solid color background.
    Solid {
        /// Background color as RGB (0.0-1.0).
        color: [f64; 3],
    },
    /// Gradient background (top to bottom).
    Gradient {
        /// Top color as RGB (0.0-1.0).
        top: [f64; 3],
        /// Bottom color as RGB (0.0-1.0).
        bottom: [f64; 3],
    },
    /// Transparent background (for compositing).
    Transparent,
}

/// Ambient occlusion settings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AmbientOcclusion {
    /// Whether AO is enabled.
    pub enabled: bool,
    /// AO intensity (0.0-2.0, default 1.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
    /// AO radius in scene units.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub radius: Option<f64>,
}

/// Bloom effect settings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Bloom {
    /// Whether bloom is enabled.
    pub enabled: bool,
    /// Bloom intensity (0.0-1.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
    /// Luminance threshold for bloom.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub threshold: Option<f64>,
}

/// Vignette effect settings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Vignette {
    /// Whether vignette is enabled.
    pub enabled: bool,
    /// Vignette offset from edge (0.0-1.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<f64>,
    /// Vignette darkness (0.0-1.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub darkness: Option<f64>,
}

/// Tone mapping algorithm.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ToneMapping {
    /// No tone mapping (linear).
    None,
    /// Reinhard tone mapping.
    Reinhard,
    /// Cineon tone mapping.
    Cineon,
    /// ACES filmic tone mapping.
    AcesFilmic,
    /// AgX tone mapping.
    AgX,
    /// Neutral tone mapping.
    Neutral,
}

/// Post-processing effects configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct PostProcessing {
    /// Ambient occlusion settings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ambient_occlusion: Option<AmbientOcclusion>,
    /// Bloom settings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bloom: Option<Bloom>,
    /// Vignette settings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vignette: Option<Vignette>,
    /// Tone mapping algorithm.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tone_mapping: Option<ToneMapping>,
    /// Exposure adjustment (-2.0 to 2.0, default 0.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exposure: Option<f64>,
}

/// A saved camera position/orientation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CameraPreset {
    /// Unique identifier for the preset.
    pub id: String,
    /// Human-readable name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Camera position in world space.
    pub position: Vec3,
    /// Camera target (look-at point).
    pub target: Vec3,
    /// Field of view in degrees.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fov: Option<f64>,
}

/// Scene-wide settings for lighting, environment, and rendering.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct SceneSettings {
    /// Environment lighting configuration.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<Environment>,
    /// Additional lights in the scene.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lights: Option<Vec<Light>>,
    /// Background configuration.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background: Option<Background>,
    /// Post-processing effects.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_processing: Option<PostProcessing>,
    /// Saved camera presets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub camera_presets: Option<Vec<CameraPreset>>,
}

/// A vcad document — the `.vcad` file format.
///
/// Contains the full IR DAG, material definitions, and scene assembly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Document {
    /// Format version string (e.g. "0.1").
    pub version: String,
    /// All nodes in the graph, keyed by [`NodeId`].
    pub nodes: HashMap<NodeId, Node>,
    /// Material definitions, keyed by name.
    pub materials: HashMap<String, MaterialDef>,
    /// Per-part material assignments (part name → material name).
    pub part_materials: HashMap<String, String>,
    /// Scene entries (assembled parts with materials).
    pub roots: Vec<SceneEntry>,

    // Scene settings (optional, for lighting/environment/post-processing)
    /// Scene-wide rendering settings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene: Option<SceneSettings>,

    // Assembly fields (optional, for kinematics)
    /// Part definitions for assembly mode.
    #[serde(rename = "partDefs", skip_serializing_if = "Option::is_none")]
    pub part_defs: Option<HashMap<String, PartDef>>,
    /// Instances of part definitions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<Instance>>,
    /// Joints connecting instances.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub joints: Option<Vec<Joint>>,
    /// The instance that is fixed in world space (ground).
    #[serde(rename = "groundInstanceId", skip_serializing_if = "Option::is_none")]
    pub ground_instance_id: Option<String>,

    // ECAD fields (optional, for PCB design)
    /// Schematic sheet for electronics design.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schematic: Option<ecad::SchematicSheet>,
    /// Legacy PCB field — migrated to PcbBoard node on load.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pcb: Option<ecad::Pcb>,
}

impl Default for Document {
    fn default() -> Self {
        Self {
            version: "0.1".to_string(),
            nodes: HashMap::new(),
            materials: HashMap::new(),
            part_materials: HashMap::new(),
            roots: Vec::new(),
            scene: None,
            part_defs: None,
            instances: None,
            joints: None,
            ground_instance_id: None,
            schematic: None,
            pcb: None,
        }
    }
}

impl Document {
    /// Create a new empty document.
    pub fn new() -> Self {
        Self::default()
    }

    /// Serialize to JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Deserialize from JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_document() {
        let mut doc = Document::new();

        // Add a cube node
        let cube_id = 1;
        doc.nodes.insert(
            cube_id,
            Node {
                id: cube_id,
                name: Some("box".to_string()),
                op: CsgOp::Cube {
                    size: Vec3::new(10.0, 20.0, 30.0),
                },
            },
        );

        // Add a cylinder node
        let cyl_id = 2;
        doc.nodes.insert(
            cyl_id,
            Node {
                id: cyl_id,
                name: Some("hole".to_string()),
                op: CsgOp::Cylinder {
                    radius: 3.0,
                    height: 40.0,
                    segments: 0,
                },
            },
        );

        // Add a difference node
        let diff_id = 3;
        doc.nodes.insert(
            diff_id,
            Node {
                id: diff_id,
                name: Some("box_with_hole".to_string()),
                op: CsgOp::Difference {
                    left: cube_id,
                    right: cyl_id,
                },
            },
        );

        // Add material
        doc.materials.insert(
            "aluminum".to_string(),
            MaterialDef {
                name: "aluminum".to_string(),
                color: [0.91, 0.92, 0.93],
                metallic: 1.0,
                roughness: 0.4,
                density: Some(2700.0),
                friction: Some(0.6),
            },
        );

        // Add scene entry
        doc.roots.push(SceneEntry {
            root: diff_id,
            material: "aluminum".to_string(),
            visible: None,
        });

        // Serialize and deserialize
        let json = doc.to_json().expect("serialize");
        let restored = Document::from_json(&json).expect("deserialize");

        assert_eq!(doc, restored);
        assert_eq!(restored.nodes.len(), 3);
        assert_eq!(restored.materials.len(), 1);
        assert_eq!(restored.roots.len(), 1);
    }

    #[test]
    fn node_graph_dag() {
        let mut doc = Document::new();

        doc.nodes.insert(
            1,
            Node {
                id: 1,
                name: None,
                op: CsgOp::Sphere {
                    radius: 5.0,
                    segments: 0,
                },
            },
        );

        doc.nodes.insert(
            2,
            Node {
                id: 2,
                name: None,
                op: CsgOp::Cube {
                    size: Vec3::new(8.0, 8.0, 8.0),
                },
            },
        );

        doc.nodes.insert(
            3,
            Node {
                id: 3,
                name: Some("rounded_cube".to_string()),
                op: CsgOp::Intersection { left: 1, right: 2 },
            },
        );

        // Verify structure
        assert_eq!(doc.nodes.len(), 3);
        match &doc.nodes[&3].op {
            CsgOp::Intersection { left, right } => {
                assert_eq!(*left, 1);
                assert_eq!(*right, 2);
            }
            _ => panic!("expected Intersection"),
        }
    }

    #[test]
    fn empty_document() {
        let doc = Document::new();
        assert_eq!(doc.version, "0.1");
        assert!(doc.nodes.is_empty());
        assert!(doc.materials.is_empty());
        assert!(doc.part_materials.is_empty());
        assert!(doc.roots.is_empty());
    }

    #[test]
    fn serde_tagged_enum() {
        let op = CsgOp::Cube {
            size: Vec3::new(1.0, 2.0, 3.0),
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"Cube""#));

        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);
    }

    #[test]
    fn sketch_operations() {
        let mut doc = Document::new();

        // Add a rectangle sketch
        let sketch_id = 1;
        doc.nodes.insert(
            sketch_id,
            Node {
                id: sketch_id,
                name: Some("rectangle".to_string()),
                op: CsgOp::Sketch2D {
                    origin: Vec3::new(0.0, 0.0, 0.0),
                    x_dir: Vec3::new(1.0, 0.0, 0.0),
                    y_dir: Vec3::new(0.0, 1.0, 0.0),
                    segments: vec![
                        SketchSegment2D::Line {
                            start: Vec2::new(0.0, 0.0),
                            end: Vec2::new(10.0, 0.0),
                        },
                        SketchSegment2D::Line {
                            start: Vec2::new(10.0, 0.0),
                            end: Vec2::new(10.0, 5.0),
                        },
                        SketchSegment2D::Line {
                            start: Vec2::new(10.0, 5.0),
                            end: Vec2::new(0.0, 5.0),
                        },
                        SketchSegment2D::Line {
                            start: Vec2::new(0.0, 5.0),
                            end: Vec2::new(0.0, 0.0),
                        },
                    ],
                },
            },
        );

        // Add an extrusion
        let extrude_id = 2;
        doc.nodes.insert(
            extrude_id,
            Node {
                id: extrude_id,
                name: Some("extruded_block".to_string()),
                op: CsgOp::Extrude {
                    sketch: sketch_id,
                    direction: Vec3::new(0.0, 0.0, 20.0),
                    twist_angle: None,
                    scale_end: None,
                },
            },
        );

        // Round-trip through JSON
        let json = doc.to_json().expect("serialize");
        let restored = Document::from_json(&json).expect("deserialize");
        assert_eq!(doc, restored);

        // Verify structure
        match &restored.nodes[&sketch_id].op {
            CsgOp::Sketch2D { segments, .. } => {
                assert_eq!(segments.len(), 4);
            }
            _ => panic!("expected Sketch2D"),
        }
        match &restored.nodes[&extrude_id].op {
            CsgOp::Extrude {
                sketch, direction, ..
            } => {
                assert_eq!(*sketch, sketch_id);
                assert_eq!(direction.z, 20.0);
            }
            _ => panic!("expected Extrude"),
        }
    }

    #[test]
    fn revolve_operation() {
        let op = CsgOp::Revolve {
            sketch: 1,
            axis_origin: Vec3::new(0.0, 0.0, 0.0),
            axis_dir: Vec3::new(0.0, 1.0, 0.0),
            angle_deg: 360.0,
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"Revolve""#));
        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);
    }

    #[test]
    fn assembly_document_roundtrip() {
        let mut doc = Document::new();

        // Add a cube node
        let cube_id = 1;
        doc.nodes.insert(
            cube_id,
            Node {
                id: cube_id,
                name: Some("base_cube".to_string()),
                op: CsgOp::Cube {
                    size: Vec3::new(10.0, 10.0, 10.0),
                },
            },
        );

        // Add a cylinder node
        let cyl_id = 2;
        doc.nodes.insert(
            cyl_id,
            Node {
                id: cyl_id,
                name: Some("arm_cylinder".to_string()),
                op: CsgOp::Cylinder {
                    radius: 2.0,
                    height: 20.0,
                    segments: 0,
                },
            },
        );

        // Add part definitions
        let mut part_defs = HashMap::new();
        part_defs.insert(
            "base".to_string(),
            PartDef {
                id: "base".to_string(),
                name: Some("Base Plate".to_string()),
                root: cube_id,
                default_material: Some("aluminum".to_string()),
            },
        );
        part_defs.insert(
            "arm".to_string(),
            PartDef {
                id: "arm".to_string(),
                name: Some("Arm".to_string()),
                root: cyl_id,
                default_material: None,
            },
        );
        doc.part_defs = Some(part_defs);

        // Add instances
        doc.instances = Some(vec![
            Instance {
                id: "base_inst".to_string(),
                part_def_id: "base".to_string(),
                name: Some("Ground Base".to_string()),
                transform: None,
                material: None,
            },
            Instance {
                id: "arm_inst".to_string(),
                part_def_id: "arm".to_string(),
                name: Some("Rotating Arm".to_string()),
                transform: Some(Transform3D {
                    translation: Vec3::new(0.0, 0.0, 10.0),
                    rotation: Vec3::new(0.0, 0.0, 0.0),
                    scale: Vec3::new(1.0, 1.0, 1.0),
                }),
                material: Some("steel".to_string()),
            },
        ]);

        // Add joints
        doc.joints = Some(vec![Joint {
            id: "joint_1".to_string(),
            name: Some("Base-Arm Revolute".to_string()),
            parent_instance_id: Some("base_inst".to_string()),
            child_instance_id: "arm_inst".to_string(),
            parent_anchor: Vec3::new(5.0, 5.0, 10.0),
            child_anchor: Vec3::new(0.0, 0.0, 0.0),
            kind: JointKind::Revolute {
                axis: Vec3::new(0.0, 0.0, 1.0),
                limits: Some((-90.0, 90.0)),
            },
            state: 0.0,
        }]);

        // Set ground instance
        doc.ground_instance_id = Some("base_inst".to_string());

        // Serialize and deserialize
        let json = doc.to_json().expect("serialize");
        let restored = Document::from_json(&json).expect("deserialize");

        assert_eq!(doc, restored);

        // Verify assembly fields
        assert!(restored.part_defs.is_some());
        assert_eq!(restored.part_defs.as_ref().unwrap().len(), 2);
        assert!(restored.instances.is_some());
        assert_eq!(restored.instances.as_ref().unwrap().len(), 2);
        assert!(restored.joints.is_some());
        assert_eq!(restored.joints.as_ref().unwrap().len(), 1);
        assert_eq!(restored.ground_instance_id, Some("base_inst".to_string()));

        // Verify camelCase serialization
        assert!(json.contains(r#""partDefs""#));
        assert!(json.contains(r#""partDefId""#));
        assert!(json.contains(r#""parentInstanceId""#));
        assert!(json.contains(r#""childInstanceId""#));
        assert!(json.contains(r#""parentAnchor""#));
        assert!(json.contains(r#""childAnchor""#));
        assert!(json.contains(r#""groundInstanceId""#));
        assert!(json.contains(r#""defaultMaterial""#));
    }

    #[test]
    fn joint_kind_serialization() {
        // Test Fixed
        let fixed = JointKind::Fixed;
        let json = serde_json::to_string(&fixed).unwrap();
        assert!(json.contains(r#""type":"Fixed""#));
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(fixed, restored);

        // Test Revolute with limits
        let revolute = JointKind::Revolute {
            axis: Vec3::new(0.0, 0.0, 1.0),
            limits: Some((-180.0, 180.0)),
        };
        let json = serde_json::to_string(&revolute).unwrap();
        assert!(json.contains(r#""type":"Revolute""#));
        assert!(json.contains(r#""axis""#));
        assert!(json.contains(r#""limits""#));
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(revolute, restored);

        // Test Revolute without limits
        let revolute_no_limits = JointKind::Revolute {
            axis: Vec3::new(1.0, 0.0, 0.0),
            limits: None,
        };
        let json = serde_json::to_string(&revolute_no_limits).unwrap();
        assert!(!json.contains(r#""limits""#)); // skip_serializing_if works
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(revolute_no_limits, restored);

        // Test Slider
        let slider = JointKind::Slider {
            axis: Vec3::new(1.0, 0.0, 0.0),
            limits: Some((0.0, 100.0)),
        };
        let json = serde_json::to_string(&slider).unwrap();
        assert!(json.contains(r#""type":"Slider""#));
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(slider, restored);

        // Test Cylindrical
        let cylindrical = JointKind::Cylindrical {
            axis: Vec3::new(0.0, 1.0, 0.0),
        };
        let json = serde_json::to_string(&cylindrical).unwrap();
        assert!(json.contains(r#""type":"Cylindrical""#));
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(cylindrical, restored);

        // Test Ball
        let ball = JointKind::Ball;
        let json = serde_json::to_string(&ball).unwrap();
        assert!(json.contains(r#""type":"Ball""#));
        let restored: JointKind = serde_json::from_str(&json).unwrap();
        assert_eq!(ball, restored);
    }

    #[test]
    fn transform3d_default() {
        let t = Transform3D::default();
        assert_eq!(t.translation, Vec3::new(0.0, 0.0, 0.0));
        assert_eq!(t.rotation, Vec3::new(0.0, 0.0, 0.0));
        assert_eq!(t.scale, Vec3::new(1.0, 1.0, 1.0));

        let t2 = Transform3D::identity();
        assert_eq!(t, t2);
    }

    #[test]
    fn sweep_operation_roundtrip() {
        let op = CsgOp::Sweep {
            sketch: 1,
            path: PathCurve::Line {
                start: Vec3::new(0.0, 0.0, 0.0),
                end: Vec3::new(0.0, 0.0, 50.0),
            },
            twist_angle: Some(std::f64::consts::PI),
            scale_start: None,
            scale_end: Some(0.5),
            orientation: None,
            path_segments: Some(32),
            arc_segments: None,
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"Sweep""#));
        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);

        // Helix path variant
        let op2 = CsgOp::Sweep {
            sketch: 2,
            path: PathCurve::Helix {
                radius: 10.0,
                pitch: 5.0,
                height: 20.0,
                turns: 4.0,
            },
            twist_angle: None,
            scale_start: None,
            scale_end: None,
            orientation: None,
            path_segments: None,
            arc_segments: None,
        };
        let json2 = serde_json::to_string(&op2).unwrap();
        let restored2: CsgOp = serde_json::from_str(&json2).unwrap();
        assert_eq!(op2, restored2);
    }

    #[test]
    fn loft_operation_roundtrip() {
        let op = CsgOp::Loft {
            sketches: vec![1, 2, 3],
            closed: Some(true),
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"Loft""#));
        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);
    }

    #[test]
    fn imported_mesh_roundtrip() {
        let op = CsgOp::ImportedMesh {
            positions: vec![0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            indices: vec![0, 1, 2],
            normals: Some(vec![0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]),
            source: Some("model.stl".to_string()),
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"ImportedMesh""#));
        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);
    }

    #[test]
    fn empty_assembly_fields_omitted() {
        let doc = Document::new();
        let json = doc.to_json().expect("serialize");

        // Assembly fields should not appear when None
        assert!(!json.contains(r#""partDefs""#));
        assert!(!json.contains(r#""instances""#));
        assert!(!json.contains(r#""joints""#));
        assert!(!json.contains(r#""groundInstanceId""#));
    }

    #[test]
    fn vec2_length() {
        assert!((Vec2::new(3.0, 4.0).length() - 5.0).abs() < 1e-12);
        assert!((Vec2::new(0.0, 0.0).length()).abs() < 1e-12);
        assert!((Vec2::new(1.0, 0.0).length() - 1.0).abs() < 1e-12);
    }

    #[test]
    fn vec2_normalize() {
        let n = Vec2::new(3.0, 4.0).normalize();
        assert!((n.length() - 1.0).abs() < 1e-12);
        assert!((n.x - 0.6).abs() < 1e-12);
        assert!((n.y - 0.8).abs() < 1e-12);
        // degenerate returns zero
        let z = Vec2::new(0.0, 0.0).normalize();
        assert!(z.x.abs() < 1e-12 && z.y.abs() < 1e-12);
    }

    #[test]
    fn vec2_dot() {
        assert!((Vec2::new(1.0, 0.0).dot(Vec2::new(0.0, 1.0))).abs() < 1e-12);
        assert!((Vec2::new(2.0, 3.0).dot(Vec2::new(4.0, 5.0)) - 23.0).abs() < 1e-12);
    }

    #[test]
    fn vec2_perp() {
        let p = Vec2::new(1.0, 0.0).perp();
        assert!((p.x - 0.0).abs() < 1e-12);
        assert!((p.y - 1.0).abs() < 1e-12);
        // perp is orthogonal
        let v = Vec2::new(3.0, 7.0);
        assert!(v.dot(v.perp()).abs() < 1e-12);
    }

    #[test]
    fn vec2_scale() {
        let s = Vec2::new(2.0, 3.0).scale(4.0);
        assert!((s.x - 8.0).abs() < 1e-12);
        assert!((s.y - 12.0).abs() < 1e-12);
    }

    #[test]
    fn vec2_ops() {
        let a = Vec2::new(1.0, 2.0);
        let b = Vec2::new(3.0, 4.0);
        let sum = a + b;
        assert!((sum.x - 4.0).abs() < 1e-12);
        assert!((sum.y - 6.0).abs() < 1e-12);
        let diff = b - a;
        assert!((diff.x - 2.0).abs() < 1e-12);
        assert!((diff.y - 2.0).abs() < 1e-12);
        let mul = a * 3.0;
        assert!((mul.x - 3.0).abs() < 1e-12);
        assert!((mul.y - 6.0).abs() < 1e-12);
        let neg = -a;
        assert!((neg.x - (-1.0)).abs() < 1e-12);
        assert!((neg.y - (-2.0)).abs() < 1e-12);
    }

    #[test]
    fn embroidery_pattern_roundtrip() {
        let op = CsgOp::EmbroideryPattern {
            design: Box::new(EmbroideryDesign {
                threads: vec![EmbroideryThread {
                    color: [255, 0, 0],
                    name: "Red".to_string(),
                }],
                stitch_groups: vec![
                    IrStitchGroup {
                        thread_index: 0,
                        stitches: vec![[0.0, 0.0], [5.0, 0.0], [5.0, 5.0]],
                        fill_params: None,
                    },
                    IrStitchGroup {
                        thread_index: 0,
                        stitches: vec![[10.0, 10.0], [15.0, 10.0]],
                        fill_params: Some(FillParams {
                            fill_type: FillType::Satin,
                            angle_deg: 45.0,
                            density_mm: 0.3,
                            underlay: true,
                            max_stitch_length_mm: 5.0,
                        }),
                    },
                ],
                hoop_width: 100.0,
                hoop_height: 100.0,
            }),
        };
        let json = serde_json::to_string(&op).unwrap();
        assert!(json.contains(r#""type":"EmbroideryPattern""#));
        let restored: CsgOp = serde_json::from_str(&json).unwrap();
        assert_eq!(op, restored);
        // Ensure fill_params is omitted when None
        assert!(!json.contains(r#""fill_params":null"#));
    }
}

#[cfg(test)]
mod tool_schema_tests {
    use super::*;

    #[test]
    fn test_tool_schemas_generated() {
        let schemas = CsgOp::tool_schemas();
        assert!(!schemas.is_empty(), "should generate at least one schema");

        // Cube should be present
        let cube = schemas
            .iter()
            .find(|s| s.name == "cube")
            .expect("cube schema missing");
        assert_eq!(cube.category, "primitive");
        assert!(
            cube.description.contains("box"),
            "cube description should mention 'box': got '{}'",
            cube.description
        );

        // Check cube has size property
        let props = cube.input_schema["properties"].as_object().unwrap();
        assert!(props.contains_key("size"), "cube should have size property");

        // Check required fields
        let required = cube.input_schema["required"].as_array().unwrap();
        assert!(
            required.iter().any(|v| v == "size"),
            "size should be required"
        );
    }

    #[test]
    fn test_hidden_variants_excluded() {
        let schemas = CsgOp::tool_schemas();
        let names: Vec<&str> = schemas.iter().map(|s| s.name.as_str()).collect();

        assert!(!names.contains(&"empty"), "Empty should be hidden");
        assert!(
            !names.contains(&"imported_mesh"),
            "ImportedMesh should be hidden"
        );
        assert!(
            !names.contains(&"step_import"),
            "StepImport should be hidden"
        );
        assert!(!names.contains(&"pcb_board"), "PcbBoard should be hidden");
        assert!(
            !names.contains(&"embroidery_pattern"),
            "EmbroideryPattern should be hidden"
        );
    }

    #[test]
    fn test_extrude_schema() {
        let schemas = CsgOp::tool_schemas();
        let extrude = schemas
            .iter()
            .find(|s| s.name == "extrude")
            .expect("extrude schema missing");
        assert_eq!(extrude.category, "sketch_op");

        let props = extrude.input_schema["properties"].as_object().unwrap();
        assert!(
            props.contains_key("sketch"),
            "extrude should have sketch property"
        );
        assert!(
            props.contains_key("direction"),
            "extrude should have direction property"
        );

        // twist_angle should not be required (it's Option<f64>)
        let required = extrude.input_schema["required"].as_array().unwrap();
        assert!(
            !required.iter().any(|v| v == "twist_angle"),
            "twist_angle should be optional"
        );
    }

    #[test]
    fn test_schema_is_valid_json() {
        let schemas = CsgOp::tool_schemas();
        // Serialize to JSON and back — confirms serde_json::Value is well-formed
        let json = serde_json::to_string(&schemas).unwrap();
        let _: Vec<ToolSchemaEntry> = serde_json::from_str(&json).unwrap();
    }

    #[test]
    fn test_categories_correct() {
        let schemas = CsgOp::tool_schemas();

        let get = |name: &str| schemas.iter().find(|s| s.name == name).unwrap();

        assert_eq!(get("cube").category, "primitive");
        assert_eq!(get("cylinder").category, "primitive");
        assert_eq!(get("sphere").category, "primitive");
        assert_eq!(get("union").category, "boolean");
        assert_eq!(get("translate").category, "transform");
        assert_eq!(get("fillet").category, "modifier");
        assert_eq!(get("extrude").category, "sketch_op");
        assert_eq!(get("linear_pattern").category, "pattern");
    }
}
