// Wraps the Vite-built single-file live viewer HTML into a TypeScript module so
// tsc emits it into dist/ and esbuild (Vercel bundle) inlines it — no runtime
// file reads, which break after bundling relocates the module. Mirrors
// scripts/wrap-viewer.mjs.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(pkgDir, "dist-live", "index.html"), "utf-8");

const out = `// Generated by scripts/wrap-live.mjs — do not edit.
/** Self-contained live review viewer HTML (Vite single-file build). */
export const LIVE_HTML: string = ${JSON.stringify(html)};
`;

writeFileSync(join(pkgDir, "src", "live-html.generated.ts"), out);
console.log(`[wrap-live] embedded ${(html.length / 1024).toFixed(0)} KB live viewer HTML`);
