// Wraps the Vite-built single-file viewer HTML into a TypeScript module so
// tsc emits it into dist/ and esbuild (Vercel bundle) inlines it — no
// runtime file reads, which break after bundling relocates the module.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(pkgDir, "dist-viewer", "index.html"), "utf-8");

const out = `// Generated by scripts/wrap-viewer.mjs — do not edit.
/** Self-contained MCP Apps viewer HTML (Vite single-file build). */
export const VIEWER_HTML: string = ${JSON.stringify(html)};
`;

writeFileSync(join(pkgDir, "src", "viewer-html.generated.ts"), out);
console.log(
  `[wrap-viewer] embedded ${(html.length / 1024).toFixed(0)} KB viewer HTML`,
);
