//! Bit-for-bit parity with the original TypeScript implementation.
//!
//! `ts_fixtures.json` was generated by running the pre-port
//! `packages/core/src/utils/print-calibration.ts` (via tsx) on the coupon
//! fixture from its vitest suite plus a float-formatting torture doc — exact
//! fingerprints, fit values, verdicts, suggestions, and summaries. The Rust
//! port must reproduce every byte.

use serde_json::{json, Value};
use vcad_kernel_calibration::{
    build_calibration_report, default_tolerance, fingerprint_document, MeasurableKind,
    PrintPrediction, ReportOptions,
};

fn fixtures() -> Value {
    serde_json::from_str(include_str!("ts_fixtures.json")).expect("fixtures parse")
}

fn prediction() -> PrintPrediction {
    serde_json::from_value(json!({
        "version": 1,
        "document_id": "doc1",
        "doc_fingerprint": fingerprint_document(&json!({ "nodes": { "1": { "op": "Cube" } } })),
        "created_at": "2026-07-07T00:00:00.000Z",
        "material": { "name": "PLA", "density_kg_m3": 1240 },
        "volume_mm3": 20000,
        "bbox_mm": { "x": 80, "y": 32, "z": 12 },
        "assumptions": ["mass assumes 100% infill"],
        "measurables": [
            { "id": "bbox_x", "label": "Overall X", "kind": "dimension", "axis": "X", "feature": "overall", "predicted": 80, "unit": "mm" },
            { "id": "bbox_y", "label": "Overall Y", "kind": "dimension", "axis": "Y", "feature": "overall", "predicted": 32, "unit": "mm" },
            { "id": "step_z_6", "label": "Step 1 height", "kind": "dimension", "axis": "Z", "feature": "step", "predicted": 6, "unit": "mm" },
            { "id": "step_z_12", "label": "Step 4 height", "kind": "dimension", "axis": "Z", "feature": "step", "predicted": 12, "unit": "mm" },
            { "id": "hole_3mm", "label": "Small hole", "kind": "diameter", "axis": "XY", "feature": "hole", "predicted": 3, "unit": "mm" },
            { "id": "hole_8mm", "label": "Large hole", "kind": "diameter", "axis": "XY", "feature": "hole", "predicted": 8, "unit": "mm" },
            { "id": "fin_1_2", "label": "Middle fin", "kind": "dimension", "axis": "X", "feature": "wall", "predicted": 1.2, "unit": "mm" },
            { "id": "mass", "label": "Part mass", "kind": "mass", "predicted": 24.8, "unit": "g" }
        ]
    }))
    .expect("prediction parses")
}

fn opts() -> ReportOptions {
    serde_json::from_value(json!({
        "recorded_at": "2026-07-08T00:00:00.000Z",
        "context": { "printer": "P1S", "material": "PLA", "process": "0.2mm layers" }
    }))
    .expect("options parse")
}

fn measure(pairs: &[(&str, f64)]) -> Vec<(String, Value)> {
    pairs
        .iter()
        .map(|(id, v)| ((*id).to_string(), json!(v)))
        .collect()
}

/// Collapse whole-valued f64s to integers so `80.0` (Rust serialization)
/// compares equal to `80` (JS serialization) — `JSON.parse` makes them the
/// same value on the consumer side.
fn normalize(v: &mut Value) {
    match v {
        Value::Number(n) => {
            if let Some(f) = n.as_f64() {
                if n.as_i64().is_none() && f.fract() == 0.0 && f.abs() < 9e15 {
                    *v = Value::from(f as i64);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(normalize),
        Value::Object(map) => map.values_mut().for_each(normalize),
        _ => {}
    }
}

fn report_value(measurements: &[(String, Value)], options: &ReportOptions) -> Value {
    let mut v = serde_json::to_value(build_calibration_report(
        &prediction(),
        measurements,
        options,
    ))
    .expect("report serializes");
    normalize(&mut v);
    v
}

#[test]
fn fingerprints_match_ts() {
    let fx = fixtures();
    assert_eq!(
        fingerprint_document(&json!({ "nodes": { "1": { "op": "Cube" } } })),
        fx["fp_cube"].as_str().unwrap()
    );
    assert_eq!(
        fingerprint_document(&json!({ "nodes": { "1": { "op": "Sphere" } } })),
        fx["fp_sphere"].as_str().unwrap()
    );
    assert_eq!(
        fingerprint_document(&json!({ "a": 1, "b": { "c": 2, "d": 3 } })),
        fx["fp_nested"].as_str().unwrap()
    );
    // Key-order independence.
    assert_eq!(
        fingerprint_document(&json!({ "b": { "d": 3, "c": 2 }, "a": 1 })),
        fx["fp_nested"].as_str().unwrap()
    );
    // Float/string formatting torture: exponents, tiny floats, -0, unicode.
    assert_eq!(
        fingerprint_document(&json!({
            "v": [1.26, -0.225, 0.1, 1e21, 1.2e-7, 123456789, -0.0],
            "s": "héllo ✓ \u{1F600}", "n": null, "t": true
        })),
        fx["fp_floats"].as_str().unwrap()
    );
}

#[test]
fn default_tolerance_matches_ts() {
    let fx = fixtures();
    let tol = fx["tol"].as_array().unwrap();
    assert_eq!(
        default_tolerance(MeasurableKind::Mass, 24.8),
        tol[0].as_f64().unwrap()
    );
    assert_eq!(
        default_tolerance(MeasurableKind::Dimension, 80.0),
        tol[1].as_f64().unwrap()
    );
    assert_eq!(
        default_tolerance(MeasurableKind::Dimension, 3.0),
        tol[2].as_f64().unwrap()
    );
}

#[test]
fn full_report_matches_ts() {
    let got = report_value(
        &measure(&[
            ("bbox_x", 79.82),
            ("bbox_y", 31.94),
            ("step_z_6", 6.02),
            ("step_z_12", 12.05),
            ("hole_3mm", 2.85),
            ("hole_8mm", 7.88),
            ("fin_1_2", 1.26),
            ("mass", 24.1),
        ]),
        &opts(),
    );
    assert_eq!(got, fixtures()["full"]);
}

#[test]
fn scale_fit_report_matches_ts() {
    let got = report_value(
        &measure(&[
            ("bbox_x", 80.0 * 0.995),
            ("bbox_y", 32.0 * 0.995),
            ("step_z_6", 6.0),
            ("step_z_12", 12.0),
            ("hole_3mm", 3.0 * 0.995),
            ("hole_8mm", 8.0 * 0.995),
            ("fin_1_2", 1.2 * 0.995),
            ("mass", 24.8),
        ]),
        &opts(),
    );
    assert_eq!(got, fixtures()["scales"]);
}

#[test]
fn offsets_report_matches_ts() {
    let got = report_value(
        &measure(&[("hole_3mm", 2.8), ("hole_8mm", 7.9), ("fin_1_2", 1.3)]),
        &opts(),
    );
    assert_eq!(got, fixtures()["offsets"]);
}

#[test]
fn partial_report_matches_ts() {
    let got = report_value(&measure(&[("bbox_x", 79.9), ("typo_id", 5.0)]), &opts());
    assert_eq!(got, fixtures()["partial"]);
}

#[test]
fn gross_error_report_matches_ts() {
    let got = report_value(&measure(&[("bbox_x", 77.0)]), &opts());
    assert_eq!(got, fixtures()["gross"]);
    assert_eq!(got["verdict"], "fail");
}

#[test]
fn stale_report_matches_ts() {
    let mut options = opts();
    options.current_doc_fingerprint = Some(fingerprint_document(
        &json!({ "nodes": { "1": { "op": "Sphere" } } }),
    ));
    let got = report_value(&measure(&[("bbox_x", 79.9)]), &options);
    assert_eq!(got, fixtures()["stale"]);
    assert_eq!(got["stale"], true);
}

#[test]
fn mass_only_report_matches_ts() {
    let got = report_value(&measure(&[("mass", 23.9)]), &opts());
    assert_eq!(got, fixtures()["massonly"]);
}
