#!/usr/bin/env node
/**
 * Reads crates/vcad-i18n/locales/*.json and generates
 * packages/core/src/i18n/translations.ts with typed translation keys.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, basename, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const localesDir = join(root, "crates/vcad-i18n/locales");
const outDir = join(root, "packages/core/src/i18n");
const outFile = join(outDir, "translations.ts");

const files = readdirSync(localesDir).filter((f) => f.endsWith(".json")).sort();

const translations = {};
for (const file of files) {
  const locale = basename(file, ".json");
  const content = JSON.parse(readFileSync(join(localesDir, file), "utf-8"));
  translations[locale] = content;
}

const locales = Object.keys(translations).sort();
if (!locales.includes("en")) {
  console.error("Error: en.json is required");
  process.exit(1);
}

let output = `// Auto-generated by scripts/gen-i18n-ts.mjs — DO NOT EDIT\n\n`;

output += `export const translations = {\n`;
for (const locale of locales) {
  const entries = translations[locale];
  output += `  "${locale}": {\n`;
  for (const [key, value] of Object.entries(entries)) {
    const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    output += `    "${key}": "${escaped}",\n`;
  }
  output += `  },\n`;
}
output += `} as const;\n\n`;

output += `export type TranslationKey = keyof typeof translations.en;\n`;
output += `export type SupportedLocale = keyof typeof translations;\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, output, "utf-8");
console.log(`Generated ${outFile} with ${locales.length} locale(s): ${locales.join(", ")}`);
