//! Part information derived from the materializer.
//!
//! Each variant tracks the IR node IDs that the materializer created for a
//! feature, enabling the UI to read/write parameters and the renderer to map
//! selections back to features.

use serde::{Deserialize, Serialize};
use vcad_ir::NodeId;

/// Information about a materialized feature (part) in the document.
///
/// Generated by the materializer as a byproduct of creating IR nodes.
/// Replaces the 17-variant `PartInfo` union type from TypeScript.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum PartInfo {
    /// A primitive shape (cube, cylinder, sphere, cone).
    #[serde(rename = "cube")]
    Cube {
        /// Part identifier (serialized FeatureId).
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Cylinder primitive.
    #[serde(rename = "cylinder")]
    Cylinder {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Sphere primitive.
    #[serde(rename = "sphere")]
    Sphere {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Cone primitive.
    #[serde(rename = "cone")]
    Cone {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Boolean operation (union, difference, intersection).
    #[serde(rename = "boolean")]
    Boolean {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Boolean type (union, difference, intersection).
        boolean_type: String,
        /// The boolean IR node.
        boolean_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// The two source part IDs.
        source_part_ids: [String; 2],
    },
    /// Extrude from sketch.
    #[serde(rename = "extrude")]
    Extrude {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The extrude IR node.
        extrude_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Revolve from sketch.
    #[serde(rename = "revolve")]
    Revolve {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The revolve IR node.
        revolve_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Sweep from sketch along path.
    #[serde(rename = "sweep")]
    Sweep {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The sweep IR node.
        sweep_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Loft between sketches.
    #[serde(rename = "loft")]
    Loft {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR nodes.
        sketch_node_ids: Vec<NodeId>,
        /// The loft IR node.
        loft_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Fillet (rounded edges).
    #[serde(rename = "fillet")]
    Fillet {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The fillet IR node.
        fillet_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Chamfer (beveled edges).
    #[serde(rename = "chamfer")]
    Chamfer {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The chamfer IR node.
        chamfer_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Shell (hollowed solid).
    #[serde(rename = "shell")]
    Shell {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The shell IR node.
        shell_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Linear pattern.
    #[serde(rename = "linear-pattern")]
    LinearPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Circular pattern.
    #[serde(rename = "circular-pattern")]
    CircularPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Mirror.
    #[serde(rename = "mirror")]
    Mirror {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The mirror IR node.
        mirror_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Text (2D text extruded to 3D).
    #[serde(rename = "text")]
    Text {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The text IR node.
        text_node_id: NodeId,
        /// The extrude IR node.
        extrude_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Imported mesh.
    #[serde(rename = "imported-mesh")]
    ImportedMesh {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The mesh IR node.
        mesh_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// Source filename.
        source: Option<String>,
    },
    /// PCB board.
    #[serde(rename = "pcb-board")]
    PcbBoard {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The board IR node.
        board_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Embroidery pattern.
    #[serde(rename = "embroidery-pattern")]
    EmbroideryPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// Source filename.
        source: Option<String>,
    },
}

impl PartInfo {
    /// Get the part ID.
    pub fn id(&self) -> &str {
        match self {
            PartInfo::Cube { id, .. }
            | PartInfo::Cylinder { id, .. }
            | PartInfo::Sphere { id, .. }
            | PartInfo::Cone { id, .. }
            | PartInfo::Boolean { id, .. }
            | PartInfo::Extrude { id, .. }
            | PartInfo::Revolve { id, .. }
            | PartInfo::Sweep { id, .. }
            | PartInfo::Loft { id, .. }
            | PartInfo::Fillet { id, .. }
            | PartInfo::Chamfer { id, .. }
            | PartInfo::Shell { id, .. }
            | PartInfo::LinearPattern { id, .. }
            | PartInfo::CircularPattern { id, .. }
            | PartInfo::Mirror { id, .. }
            | PartInfo::Text { id, .. }
            | PartInfo::ImportedMesh { id, .. }
            | PartInfo::PcbBoard { id, .. }
            | PartInfo::EmbroideryPattern { id, .. } => id,
        }
    }

    /// Get the root (outermost) node ID for this part.
    pub fn root_node_id(&self) -> NodeId {
        match self {
            PartInfo::Cube {
                translate_node_id, ..
            }
            | PartInfo::Cylinder {
                translate_node_id, ..
            }
            | PartInfo::Sphere {
                translate_node_id, ..
            }
            | PartInfo::Cone {
                translate_node_id, ..
            }
            | PartInfo::Boolean {
                translate_node_id, ..
            }
            | PartInfo::Extrude {
                translate_node_id, ..
            }
            | PartInfo::Revolve {
                translate_node_id, ..
            }
            | PartInfo::Sweep {
                translate_node_id, ..
            }
            | PartInfo::Loft {
                translate_node_id, ..
            }
            | PartInfo::Fillet {
                translate_node_id, ..
            }
            | PartInfo::Chamfer {
                translate_node_id, ..
            }
            | PartInfo::Shell {
                translate_node_id, ..
            }
            | PartInfo::LinearPattern {
                translate_node_id, ..
            }
            | PartInfo::CircularPattern {
                translate_node_id, ..
            }
            | PartInfo::Mirror {
                translate_node_id, ..
            }
            | PartInfo::Text {
                translate_node_id, ..
            }
            | PartInfo::ImportedMesh {
                translate_node_id, ..
            }
            | PartInfo::PcbBoard {
                translate_node_id, ..
            }
            | PartInfo::EmbroideryPattern {
                translate_node_id, ..
            } => *translate_node_id,
        }
    }
}
