//! Part information derived from the materializer.
//!
//! Each variant tracks the IR node IDs that the materializer created for a
//! feature, enabling the UI to read/write parameters and the renderer to map
//! selections back to features.

use serde::{Deserialize, Serialize};
use vcad_ir::NodeId;

/// Information about a materialized feature (part) in the document.
///
/// Generated by the materializer as a byproduct of creating IR nodes.
/// Replaces the 17-variant `PartInfo` union type from TypeScript.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum PartInfo {
    /// A primitive shape (cube, cylinder, sphere, cone).
    #[serde(rename = "cube", rename_all = "camelCase")]
    Cube {
        /// Part identifier (serialized FeatureId).
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Cylinder primitive.
    #[serde(rename = "cylinder", rename_all = "camelCase")]
    Cylinder {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Sphere primitive.
    #[serde(rename = "sphere", rename_all = "camelCase")]
    Sphere {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Cone primitive.
    #[serde(rename = "cone", rename_all = "camelCase")]
    Cone {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The primitive IR node.
        primitive_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Boolean operation (union, difference, intersection).
    #[serde(rename = "boolean", rename_all = "camelCase")]
    Boolean {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Boolean type (union, difference, intersection).
        boolean_type: String,
        /// The boolean IR node.
        boolean_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// The two source part IDs.
        source_part_ids: [String; 2],
    },
    /// Extrude from sketch.
    #[serde(rename = "extrude", rename_all = "camelCase")]
    Extrude {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The extrude IR node.
        extrude_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Revolve from sketch.
    #[serde(rename = "revolve", rename_all = "camelCase")]
    Revolve {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The revolve IR node.
        revolve_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Sweep from sketch along path.
    #[serde(rename = "sweep", rename_all = "camelCase")]
    Sweep {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR node.
        sketch_node_id: NodeId,
        /// The sweep IR node.
        sweep_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Loft between sketches.
    #[serde(rename = "loft", rename_all = "camelCase")]
    Loft {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The sketch IR nodes.
        sketch_node_ids: Vec<NodeId>,
        /// The loft IR node.
        loft_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Fillet (rounded edges).
    #[serde(rename = "fillet", rename_all = "camelCase")]
    Fillet {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The fillet IR node.
        fillet_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Chamfer (beveled edges).
    #[serde(rename = "chamfer", rename_all = "camelCase")]
    Chamfer {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The chamfer IR node.
        chamfer_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Shell (hollowed solid).
    #[serde(rename = "shell", rename_all = "camelCase")]
    Shell {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The shell IR node.
        shell_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Linear pattern.
    #[serde(rename = "linear-pattern", rename_all = "camelCase")]
    LinearPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Circular pattern.
    #[serde(rename = "circular-pattern", rename_all = "camelCase")]
    CircularPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Mirror.
    #[serde(rename = "mirror", rename_all = "camelCase")]
    Mirror {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// Source part ID.
        source_part_id: String,
        /// The mirror IR node.
        mirror_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Text (2D text extruded to 3D).
    #[serde(rename = "text", rename_all = "camelCase")]
    Text {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The text IR node.
        text_node_id: NodeId,
        /// The extrude IR node.
        extrude_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Imported mesh.
    #[serde(rename = "imported-mesh", rename_all = "camelCase")]
    ImportedMesh {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The mesh IR node.
        mesh_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// Source filename.
        source: Option<String>,
    },
    /// PCB board.
    #[serde(rename = "pcb-board", rename_all = "camelCase")]
    PcbBoard {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The board IR node.
        board_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
    },
    /// Embroidery pattern.
    #[serde(rename = "embroidery-pattern", rename_all = "camelCase")]
    EmbroideryPattern {
        /// Part identifier.
        id: String,
        /// Human-readable name.
        name: String,
        /// The pattern IR node.
        pattern_node_id: NodeId,
        /// Scale transform node.
        scale_node_id: NodeId,
        /// Rotation transform node.
        rotate_node_id: NodeId,
        /// Translation transform node.
        translate_node_id: NodeId,
        /// Source filename.
        source: Option<String>,
    },
}

impl PartInfo {
    /// Get the part ID.
    pub fn id(&self) -> &str {
        match self {
            PartInfo::Cube { id, .. }
            | PartInfo::Cylinder { id, .. }
            | PartInfo::Sphere { id, .. }
            | PartInfo::Cone { id, .. }
            | PartInfo::Boolean { id, .. }
            | PartInfo::Extrude { id, .. }
            | PartInfo::Revolve { id, .. }
            | PartInfo::Sweep { id, .. }
            | PartInfo::Loft { id, .. }
            | PartInfo::Fillet { id, .. }
            | PartInfo::Chamfer { id, .. }
            | PartInfo::Shell { id, .. }
            | PartInfo::LinearPattern { id, .. }
            | PartInfo::CircularPattern { id, .. }
            | PartInfo::Mirror { id, .. }
            | PartInfo::Text { id, .. }
            | PartInfo::ImportedMesh { id, .. }
            | PartInfo::PcbBoard { id, .. }
            | PartInfo::EmbroideryPattern { id, .. } => id,
        }
    }

    /// Get the root (outermost) node ID for this part.
    pub fn root_node_id(&self) -> NodeId {
        match self {
            PartInfo::Cube {
                translate_node_id, ..
            }
            | PartInfo::Cylinder {
                translate_node_id, ..
            }
            | PartInfo::Sphere {
                translate_node_id, ..
            }
            | PartInfo::Cone {
                translate_node_id, ..
            }
            | PartInfo::Boolean {
                translate_node_id, ..
            }
            | PartInfo::Extrude {
                translate_node_id, ..
            }
            | PartInfo::Revolve {
                translate_node_id, ..
            }
            | PartInfo::Sweep {
                translate_node_id, ..
            }
            | PartInfo::Loft {
                translate_node_id, ..
            }
            | PartInfo::Fillet {
                translate_node_id, ..
            }
            | PartInfo::Chamfer {
                translate_node_id, ..
            }
            | PartInfo::Shell {
                translate_node_id, ..
            }
            | PartInfo::LinearPattern {
                translate_node_id, ..
            }
            | PartInfo::CircularPattern {
                translate_node_id, ..
            }
            | PartInfo::Mirror {
                translate_node_id, ..
            }
            | PartInfo::Text {
                translate_node_id, ..
            }
            | PartInfo::ImportedMesh {
                translate_node_id, ..
            }
            | PartInfo::PcbBoard {
                translate_node_id, ..
            }
            | PartInfo::EmbroideryPattern {
                translate_node_id, ..
            } => *translate_node_id,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_serde_camel_case_roundtrip() {
        let part = PartInfo::Cube {
            id: "1:0".to_string(),
            name: "Box 1".to_string(),
            primitive_node_id: 1,
            scale_node_id: 2,
            rotate_node_id: 3,
            translate_node_id: 4,
        };

        let json = serde_json::to_string(&part).unwrap();

        // Verify camelCase field names
        assert!(
            json.contains("\"primitiveNodeId\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"scaleNodeId\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"rotateNodeId\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"translateNodeId\""),
            "expected camelCase: {json}"
        );

        // Verify variant name still uses explicit rename
        assert!(
            json.contains("\"kind\":\"cube\""),
            "expected kind=cube: {json}"
        );

        // Verify snake_case is NOT in output
        assert!(
            !json.contains("primitive_node_id"),
            "unexpected snake_case: {json}"
        );

        // Roundtrip
        let deserialized: PartInfo = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.id(), "1:0");
        assert_eq!(deserialized.root_node_id(), 4);
    }

    #[test]
    fn test_serde_boolean_camel_case() {
        let part = PartInfo::Boolean {
            id: "1:1".to_string(),
            name: "Union 1".to_string(),
            boolean_type: "union".to_string(),
            boolean_node_id: 5,
            scale_node_id: 6,
            rotate_node_id: 7,
            translate_node_id: 8,
            source_part_ids: ["1:0".to_string(), "1:2".to_string()],
        };

        let json = serde_json::to_string(&part).unwrap();
        assert!(
            json.contains("\"booleanType\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"booleanNodeId\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"sourcePartIds\""),
            "expected camelCase: {json}"
        );

        let deserialized: PartInfo = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.id(), "1:1");
    }

    #[test]
    fn test_serde_loft_camel_case() {
        let part = PartInfo::Loft {
            id: "1:3".to_string(),
            name: "Loft 1".to_string(),
            sketch_node_ids: vec![1, 2],
            loft_node_id: 3,
            scale_node_id: 4,
            rotate_node_id: 5,
            translate_node_id: 6,
        };

        let json = serde_json::to_string(&part).unwrap();
        assert!(
            json.contains("\"sketchNodeIds\""),
            "expected camelCase: {json}"
        );
        assert!(
            json.contains("\"loftNodeId\""),
            "expected camelCase: {json}"
        );

        let deserialized: PartInfo = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.id(), "1:3");
    }
}
